### ISSUE TITLE
The plugin crashes when content is nil

### ISSUE THREAD

**Issue by shinnkondo** [yterajima/middleman-gemoji#7]
The following error was thrown when I generated an Haml file for a layout file and moved the original file to somewhere else while middleman server was running.

``` sh
NoMethodError: undefined method `to_str' for nil:NilClass
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-gemoji-0.0.5/lib/middleman-gemoji/extension.rb:25:in `emojify'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/middleman-gemoji-0.0.5/lib/middleman-gemoji/extension.rb:19:in `block in initialize'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/uber-0.0.13/lib/uber/options.rb:80:in `instance_exec'
...
...
```

This seems caused by `content` to be `nil`. I believe that the if statement at https://github.com/yterajima/middleman-gemoji/blob/master/lib/middleman-gemoji/extension.rb#L37 should be moved to L38, to properly check if `content` is not `nil` before a method is called on it.

I am not sure exactly when middleman passes empty content to an extension. I tried simple renaming, changing extension or duplicating file and deleting one while the server is running, but none of them made `content` to be `nil` or caused the same error. (and thus I don't know what kind of tests I should write.)

Perhaps the better way to test this kind of things is to have an unit test which calls the internal functions directly, but I am not dare to choose a testing framework here. 

Would you fix this? I can write a pull request for a fix if you are wiling to accept code without a test case.

**Comment by yuya-matsushima** [comment]
Thank you for letting me know . I will be fixed this bug.

It seemd Middleman's hook is broken. https://travis-ci.org/yterajima/middleman-gemoji/builds/92427181

Likely to take a long time because it modified from investigating .

**Comment by yuya-matsushima** [comment]
v0.0.8 is released. Now fix this trouble.

https://github.com/yterajima/middleman-gemoji/commit/42fbc311e3bc15b15c9b1ae6a72a6218dab6cd84#diff-581053d6b4e67464b3fc48704a94631dR19
